const { describe, it, before, after } = require('node:test');
const assert = require('node:assert');
const http = require('http');
const app = require('../src/app');

describe('Sprint 1 End-to-End Live Integration: Node -> Python -> NetworkX', () => {
  let server;
  let baseUrl;
  let createdCaseId;

  before(async () => {
    server = http.createServer(app);
    await new Promise((resolve) => server.listen(0, resolve));
    const port = server.address().port;
    baseUrl = `http://localhost:${port}`;
  });

  after(() => {
    server.close();
  });

  it('1. GET /health verifies Node backend liveness', async () => {
    const res = await fetch(`${baseUrl}/health`);
    assert.strictEqual(res.status, 200);
    const body = await res.json();
    assert.strictEqual(body.status, 'ok');
    assert.strictEqual(body.service, 'tracevault-backend');
  });

  it('2. GET /health/intelligence verifies live connection to Python service', async () => {
    const res = await fetch(`${baseUrl}/health/intelligence`);
    assert.strictEqual(res.status, 200);
    const body = await res.json();
    assert.strictEqual(body.status, 'ok');
    assert.strictEqual(body.intelligence_service.reachable, true);
  });

  it('3. POST /api/cases creates an investigation case', async () => {
    const payload = {
      title: 'E2E Live Cybercrime Case',
      description: 'Live test tracing suspect unhosted wallet',
      priority: 'CRITICAL',
      crime_type: 'RANSOMWARE'
    };

    const res = await fetch(`${baseUrl}/api/cases`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload)
    });

    assert.strictEqual(res.status, 201);
    const body = await res.json();
    assert.strictEqual(body.success, true);
    assert.ok(body.data.case_id);
    createdCaseId = body.data.case_id;
  });

  it('4. GET /api/cases lists cases including created case', async () => {
    const res = await fetch(`${baseUrl}/api/cases`);
    assert.strictEqual(res.status, 200);
    const body = await res.json();
    assert.strictEqual(body.success, true);
    const found = body.data.some(c => c.case_id === createdCaseId);
    assert.strictEqual(found, true);
  });

  it('5. GET /api/cases/:id retrieves created case details', async () => {
    const res = await fetch(`${baseUrl}/api/cases/${createdCaseId}`);
    assert.strictEqual(res.status, 200);
    const body = await res.json();
    assert.strictEqual(body.success, true);
    assert.strictEqual(body.data.case_id, createdCaseId);
    assert.strictEqual(body.data.priority, 'CRITICAL');
  });

  it('6. POST /api/cases/:id/analyze executes full live Node -> Python -> NetworkX pipeline', async () => {
    const payload = {
      wallet_address: 'A',
      blockchain: 'ethereum'
    };

    const res = await fetch(`${baseUrl}/api/cases/${createdCaseId}/analyze`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload)
    });

    assert.strictEqual(res.status, 200);
    const body = await res.json();
    assert.strictEqual(body.success, true);

    const result = body.data;
    assert.strictEqual(result.case_id, createdCaseId);
    assert.strictEqual(result.wallet, 'A');
    assert.strictEqual(result.blockchain, 'ethereum');

    // Verify VASP attribution generated by Python + NetworkX BFS
    assert.ok(result.nearest_vasp, 'nearest_vasp must be returned');
    assert.strictEqual(result.nearest_vasp.name, 'Example Exchange');
    assert.strictEqual(result.nearest_vasp.distance, 3);
    assert.ok(result.nearest_vasp.confidence > 0, 'Confidence must be positive');

    // Verify Risk scoring
    assert.ok(result.risk, 'Risk object must be returned');
    assert.ok(result.risk.score > 0, 'Risk score must be positive');
    assert.ok(['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'].includes(result.risk.level));

    // Verify Path from NetworkX
    assert.ok(Array.isArray(result.path), 'Path must be an array of hops');
    assert.ok(result.path.length >= 1, 'Path must contain at least one hop');

    // Verify Evidence list
    assert.ok(Array.isArray(result.evidence), 'Evidence must be an array');
  });

  it('7. GET /api/cases/:id/results retrieves persisted analysis results', async () => {
    const res = await fetch(`${baseUrl}/api/cases/${createdCaseId}/results`);
    assert.strictEqual(res.status, 200);
    const body = await res.json();
    assert.strictEqual(body.success, true);
    assert.strictEqual(body.count, 1);
    assert.strictEqual(body.data[0].nearest_vasp.name, 'Example Exchange');
  });

  it('8. POST /api/cases/:id/disclosure-request drafts SAHYOG request based on analysis', async () => {
    const res = await fetch(`${baseUrl}/api/cases/${createdCaseId}/disclosure-request`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        purpose: 'Section 91 CrPC Lawful Disclosure'
      })
    });

    assert.strictEqual(res.status, 201);
    const body = await res.json();
    assert.strictEqual(body.success, true);
    assert.strictEqual(body.data.target_vasp, 'Example Exchange');
    assert.strictEqual(body.data.adapter, 'MOCK_SAHYOG_SANDBOX_ADAPTER');
  });
});
