from datetime import datetime, timezone
from decimal import Decimal
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, ConfigDict, Field, model_validator

from app.models.analysis import EvidenceItem, RiskResult, RiskSignal
from app.upi.models import UPITransaction


class UPIFraudSignalType:
    """Standardized risk signal typologies for UPI fraud intelligence."""
    NEW_BENEFICIARY = "NEW_BENEFICIARY"
    HIGH_TRANSACTION_VELOCITY = "HIGH_TRANSACTION_VELOCITY"
    TRANSACTION_BURST = "TRANSACTION_BURST"
    UNUSUAL_AMOUNT = "UNUSUAL_AMOUNT"
    MULTIPLE_FAILED_ATTEMPTS = "MULTIPLE_FAILED_ATTEMPTS"
    NEW_DEVICE = "NEW_DEVICE"
    UNUSUAL_TRANSACTION_TIME = "UNUSUAL_TRANSACTION_TIME"
    BENEFICIARY_BURST = "BENEFICIARY_BURST"
    HIGH_VALUE_VELOCITY = "HIGH_VALUE_VELOCITY"
    RAPID_PASS_THROUGH = "RAPID_PASS_THROUGH"


class UPIFraudFinding(BaseModel):
    """
    Atomic fraud risk finding generated by a deterministic behavioral rule.
    Phrased objectively as an investigative signal requiring review.
    """
    model_config = ConfigDict(arbitrary_types_allowed=True, populate_by_name=True)

    signal_id: str = Field(..., description="Unique finding identifier (e.g. UPI-SIG-01)")
    signal_type: str = Field(..., description="Classification type from UPIFraudSignalType")
    severity: str = Field(default="MEDIUM", description="Severity tier: LOW, MEDIUM, HIGH, CRITICAL")
    confidence: float = Field(default=80.0, ge=0.0, le=100.0, description="Rule confidence (0-100)")
    risk_contribution: float = Field(default=15.0, ge=0.0, le=100.0, description="Risk point contribution")
    title: str = Field(..., description="Human-readable finding title")
    description: str = Field(..., description="Investigative finding description")
    reason: str = Field(..., description="Explainable rationale and criteria trigger")
    transaction_ids: List[str] = Field(default_factory=list, description="Associated transaction IDs")
    affected_entities: List[str] = Field(default_factory=list, description="Counterparties or VPAs involved")
    metrics: Dict[str, Any] = Field(default_factory=dict, description="Quantitative rule metrics")

    def to_risk_signal(self) -> RiskSignal:
        """Converts finding into canonical TRACEVAULT RiskSignal."""
        return RiskSignal(
            id=self.signal_id,
            signal_type=self.signal_type,
            score=self.risk_contribution,
            contribution=self.risk_contribution,
            description=self.title,
            severity=self.severity,
            entity=self.affected_entities[0] if self.affected_entities else None,
            evidence=f"{self.description} | {self.reason}",
            status="Detected",
            reason=self.reason,
            metadata=self.metrics,
        )

    def to_evidence_item(self, timestamp: Optional[str] = None) -> EvidenceItem:
        """Converts finding into canonical TRACEVAULT EvidenceItem."""
        ts = timestamp or datetime.now(timezone.utc).isoformat()
        return EvidenceItem(
            id=f"EV-{self.signal_id}",
            type="UPI_SIGNAL",
            description=f"Potential fraud-risk signal detected: {self.title} - {self.description}",
            source="upi_rules_engine",
            timestamp=ts,
            status="Detected",
            relevance=self.severity,
            entity=self.affected_entities[0] if self.affected_entities else None,
            metadata={
                "signal_type": self.signal_type,
                "risk_contribution": self.risk_contribution,
                "confidence": self.confidence,
                "transaction_ids": self.transaction_ids,
                "metrics": self.metrics,
                "reason": self.reason,
            },
        )

    def to_dict(self) -> Dict[str, Any]:
        return {
            "signal_id": self.signal_id,
            "signal_type": self.signal_type,
            "severity": self.severity,
            "confidence": self.confidence,
            "risk_contribution": self.risk_contribution,
            "title": self.title,
            "description": self.description,
            "reason": self.reason,
            "transaction_ids": self.transaction_ids,
            "affected_entities": self.affected_entities,
            "metrics": self.metrics,
        }


class UPIFeatures(BaseModel):
    """
    Extracted quantitative and behavioral features from current and baseline UPI transactions.
    """
    model_config = ConfigDict(arbitrary_types_allowed=True, populate_by_name=True)

    transaction_count: int = Field(default=0, ge=0)
    total_volume: Decimal = Field(default=Decimal("0.0"))
    avg_amount: Decimal = Field(default=Decimal("0.0"))
    max_amount: Decimal = Field(default=Decimal("0.0"))
    min_amount: Decimal = Field(default=Decimal("0.0"))
    median_amount: Decimal = Field(default=Decimal("0.0"))
    time_span_seconds: float = Field(default=0.0, ge=0.0)
    velocity_tx_per_minute: float = Field(default=0.0, ge=0.0)
    unique_beneficiaries: int = Field(default=0, ge=0)
    failed_attempt_count: int = Field(default=0, ge=0)
    new_beneficiary_count: int = Field(default=0, ge=0)
    new_device_count: int = Field(default=0, ge=0)
    has_baseline: bool = Field(default=False)
    baseline_tx_count: int = Field(default=0, ge=0)
    baseline_avg_amount: Optional[Decimal] = Field(default=None)
    baseline_max_amount: Optional[Decimal] = Field(default=None)
    baseline_median_amount: Optional[Decimal] = Field(default=None)
    amount_deviation_ratio: Optional[float] = Field(default=None)
    is_unusual_hour: bool = Field(default=False)
    pass_through_detected: bool = Field(default=False)
    known_beneficiaries: List[str] = Field(default_factory=list)
    new_beneficiaries: List[str] = Field(default_factory=list)
    devices_used: List[str] = Field(default_factory=list)
    metadata: Dict[str, Any] = Field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "transaction_count": self.transaction_count,
            "total_volume": str(self.total_volume),
            "avg_amount": str(self.avg_amount),
            "max_amount": str(self.max_amount),
            "min_amount": str(self.min_amount),
            "median_amount": str(self.median_amount),
            "time_span_seconds": self.time_span_seconds,
            "velocity_tx_per_minute": self.velocity_tx_per_minute,
            "unique_beneficiaries": self.unique_beneficiaries,
            "failed_attempt_count": self.failed_attempt_count,
            "new_beneficiary_count": self.new_beneficiary_count,
            "new_device_count": self.new_device_count,
            "has_baseline": self.has_baseline,
            "baseline_tx_count": self.baseline_tx_count,
            "baseline_avg_amount": str(self.baseline_avg_amount) if self.baseline_avg_amount is not None else None,
            "baseline_max_amount": str(self.baseline_max_amount) if self.baseline_max_amount is not None else None,
            "baseline_median_amount": str(self.baseline_median_amount) if self.baseline_median_amount is not None else None,
            "amount_deviation_ratio": self.amount_deviation_ratio,
            "is_unusual_hour": self.is_unusual_hour,
            "pass_through_detected": self.pass_through_detected,
            "known_beneficiaries": self.known_beneficiaries,
            "new_beneficiaries": self.new_beneficiaries,
            "devices_used": self.devices_used,
            "metadata": self.metadata,
        }


class UPIFraudAnalysisResult(BaseModel):
    """
    Explainable investigation result for UPI fraud intelligence.
    Harmonized with TRACEVAULT canonical risk and evidence architectures.
    """
    model_config = ConfigDict(arbitrary_types_allowed=True, populate_by_name=True)

    subject: str = Field(..., description="Investigated subject VPA")
    analyzed_transactions: List[UPITransaction] = Field(default_factory=list)
    features: UPIFeatures = Field(...)
    findings: List[UPIFraudFinding] = Field(default_factory=list)
    risk: RiskResult = Field(...)
    evidence: List[EvidenceItem] = Field(default_factory=list)
    reasoning_trace: List[str] = Field(default_factory=list)
    data_source: str = Field(default="mock_upi")
    baseline_metadata: Dict[str, Any] = Field(default_factory=dict)
    metadata: Dict[str, Any] = Field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "subject": self.subject,
            "analyzed_transactions": [tx.to_dict() for tx in self.analyzed_transactions],
            "features": self.features.to_dict(),
            "findings": [f.to_dict() for f in self.findings],
            "risk": self.risk.to_dict(),
            "evidence": [e.to_dict() for e in self.evidence],
            "reasoning_trace": self.reasoning_trace,
            "data_source": self.data_source,
            "baseline_metadata": self.baseline_metadata,
            "metadata": self.metadata,
        }
