from typing import Any, Dict

INVESTIGATION_SCENARIOS: Dict[str, Dict[str, Any]] = {
    # INV-001: Crypto-Only Investigation (CASE-2026-001 Regression Parity)
    "INV-001": {
        "scenario_id": "INV-001",
        "case_id": "CASE-2026-001",
        "title": "Crypto Peeling Chain to Exchange Deposit",
        "description": "Standard 3-hop crypto peeling and layering flow leading to Example Exchange deposit.",
        "subject_type": "wallet",
        "subject_id": "0x71c83408a6cf2372e9a5957b6d193d56f6c91350",
        "rail_scope": "CRYPTO",
        "synthetic": True,
        "provenance": "MOCK",
        "crypto_transactions": [
            {
                "transaction_hash": "0xaaa001",
                "blockchain": "ethereum",
                "timestamp": "2026-09-28T09:00:00Z",
                "from_address": "0x71c83408a6cf2372e9a5957b6d193d56f6c91350",
                "to_address": "0x28a8746e75304c0780e011bed21c72cd78cd535e",
                "asset": "ETH",
                "amount": 10.0,
                "transaction_type": "transfer",
                "source": "blockchain",
            },
            {
                "transaction_hash": "0xaaa002",
                "blockchain": "ethereum",
                "timestamp": "2026-09-28T09:30:00Z",
                "from_address": "0x28a8746e75304c0780e011bed21c72cd78cd535e",
                "to_address": "0x0000000000000000000000000000000000000001",
                "asset": "ETH",
                "amount": 9.8,
                "transaction_type": "transfer",
                "source": "blockchain",
            },
            {
                "transaction_hash": "0xaaa003",
                "blockchain": "ethereum",
                "timestamp": "2026-09-28T10:00:00Z",
                "from_address": "0x0000000000000000000000000000000000000001",
                "to_address": "0x9999999999999999999999999999999999999999",
                "asset": "ETH",
                "amount": 9.5,
                "transaction_type": "transfer",
                "source": "blockchain",
            },
        ],
        "vasp_attributions": [
            {
                "wallet_address": "0x9999999999999999999999999999999999999999",
                "vasp_name": "Example Exchange",
                "deposit_address": "0x9999999999999999999999999999999999999999",
                "risk_score": 60.0,
            }
        ],
        "upi_transactions": [],
        "location_signals": [],
        "cross_rail_associations": [],
        "expected_risk_level": "HIGH",
        "expected_status": "COMPLETE",
    },

    # INV-002: Pure UPI Fraud Investigation
    "INV-002": {
        "scenario_id": "INV-002",
        "case_id": "CASE-UPI-MULE-002",
        "title": "UPI Mule Account Funnel & Merchant Exit",
        "description": "Rapid multi-hop UPI dispersion funneling to a high-risk merchant account.",
        "subject_type": "upi_vpa",
        "subject_id": "source_fraudster@mockupi",
        "rail_scope": "UPI",
        "synthetic": True,
        "provenance": "MOCK",
        "crypto_transactions": [],
        "vasp_attributions": [],
        "upi_transactions": [
            {
                "transaction_id": "UPI-TXN-002-1",
                "timestamp": "2026-09-28T11:00:00Z",
                "amount": 100000.0,
                "currency": "INR",
                "sender_vpa": "source_fraudster@mockupi",
                "receiver_vpa": "mule_primary@mockupi",
                "sender_bank": "HDFC",
                "receiver_bank": "ICICI",
                "payment_app": "PhonePe",
                "transaction_type": "P2P",
                "status": "SUCCESS",
            },
            {
                "transaction_id": "UPI-TXN-002-2",
                "timestamp": "2026-09-28T11:05:00Z",
                "amount": 50000.0,
                "currency": "INR",
                "sender_vpa": "mule_primary@mockupi",
                "receiver_vpa": "mule_sub1@mockupi",
                "sender_bank": "ICICI",
                "receiver_bank": "SBI",
                "payment_app": "GPay",
                "transaction_type": "P2P",
                "status": "SUCCESS",
            },
            {
                "transaction_id": "UPI-TXN-002-3",
                "timestamp": "2026-09-28T11:08:00Z",
                "amount": 49000.0,
                "currency": "INR",
                "sender_vpa": "mule_sub1@mockupi",
                "receiver_vpa": "crypto_merchant@mockupi",
                "sender_bank": "SBI",
                "receiver_bank": "AXIS",
                "merchant_id": "MERCH_CRYPTO_001",
                "merchant_category": "6051",
                "transaction_type": "P2M",
                "status": "SUCCESS",
            },
        ],
        "location_signals": [],
        "cross_rail_associations": [],
        "expected_risk_level": "HIGH",
        "expected_status": "COMPLETE",
    },

    # INV-003: Multi-Rail Independent Datasets
    "INV-003": {
        "scenario_id": "INV-003",
        "case_id": "CASE-INDEPENDENT-003",
        "title": "Concurrent Independent Crypto and UPI Activity",
        "description": "Concurrent activity across both crypto and UPI rails without analytical cross-rail link.",
        "subject_type": "case",
        "subject_id": "CASE-INDEPENDENT-003",
        "rail_scope": "MULTI_RAIL",
        "synthetic": True,
        "provenance": "MOCK",
        "crypto_transactions": [
            {
                "transaction_hash": "0xbbb001",
                "blockchain": "ethereum",
                "timestamp": "2026-09-28T12:00:00Z",
                "from_address": "0x1111111111111111111111111111111111111111",
                "to_address": "0x2222222222222222222222222222222222222222",
                "asset": "USDT",
                "amount": 5000.0,
                "transaction_type": "transfer",
            }
        ],
        "vasp_attributions": [],
        "upi_transactions": [
            {
                "transaction_id": "UPI-TXN-003-1",
                "timestamp": "2026-09-28T12:05:00Z",
                "amount": 25000.0,
                "currency": "INR",
                "sender_vpa": "user_a@mockupi",
                "receiver_vpa": "user_b@mockupi",
                "transaction_type": "P2P",
                "status": "SUCCESS",
            }
        ],
        "location_signals": [],
        "cross_rail_associations": [],
        "expected_risk_level": "MEDIUM",
        "expected_status": "COMPLETE",
    },

    # INV-004: Explicit Synthetic Cross-Rail Investigation
    "INV-004": {
        "scenario_id": "INV-004",
        "case_id": "CASE-CROSS-RAIL-004",
        "title": "Crypto Theft Off-Ramp to UPI P2P Cash-Out",
        "description": "Correlated off-ramp order matching crypto deposit to UPI settlement VPA with cash-out chain.",
        "subject_type": "wallet",
        "subject_id": "0xvictimwallet000000000000000000000000001",
        "rail_scope": "MULTI_RAIL",
        "synthetic": True,
        "provenance": "SYNTHETIC",
        "crypto_transactions": [
            {
                "transaction_hash": "0xccc001",
                "blockchain": "ethereum",
                "timestamp": "2026-09-28T13:00:00Z",
                "from_address": "0xvictimwallet000000000000000000000000001",
                "to_address": "0xlaundererwallet000000000000000000000001",
                "asset": "ETH",
                "amount": 15.0,
                "transaction_type": "transfer",
            },
            {
                "transaction_hash": "0xccc002",
                "blockchain": "ethereum",
                "timestamp": "2026-09-28T13:20:00Z",
                "from_address": "0xlaundererwallet000000000000000000000001",
                "to_address": "0xofframpdeposit0000000000000000000000001",
                "asset": "ETH",
                "amount": 14.8,
                "transaction_type": "transfer",
            },
        ],
        "vasp_attributions": [
            {
                "wallet_address": "0xofframpdeposit0000000000000000000000001",
                "vasp_name": "CoinDelta Exchange",
                "deposit_address": "0xofframpdeposit0000000000000000000000001",
                "risk_score": 75.0,
            }
        ],
        "cross_rail_associations": [
            {
                "source_node_id": "wallet:0xofframpdeposit0000000000000000000000001",
                "target_node_id": "upi:p2p_desk@mockupi",
                "source_rail": "CRYPTO",
                "target_rail": "UPI",
                "confidence": 90.0,
                "description": "SYNTHETIC DEMONSTRATION ASSOCIATION: Off-ramp order payout matched to UPI settlement VPA.",
                "source": "exchange_offramp_audit_log",
            }
        ],
        "upi_transactions": [
            {
                "transaction_id": "UPI-TXN-004-1",
                "timestamp": "2026-09-28T13:40:00Z",
                "amount": 1200000.0,
                "currency": "INR",
                "sender_vpa": "p2p_desk@mockupi",
                "receiver_vpa": "cashout_master@mockupi",
                "sender_bank": "HDFC",
                "receiver_bank": "KOTAK",
                "transaction_type": "P2P",
                "status": "SUCCESS",
            },
            {
                "transaction_id": "UPI-TXN-004-2",
                "timestamp": "2026-09-28T13:45:00Z",
                "amount": 300000.0,
                "currency": "INR",
                "sender_vpa": "cashout_master@mockupi",
                "receiver_vpa": "mule_atm_runner@mockupi",
                "sender_bank": "KOTAK",
                "receiver_bank": "ICICI",
                "transaction_type": "P2P",
                "status": "SUCCESS",
            },
        ],
        "location_signals": [],
        "expected_risk_level": "CRITICAL",
        "expected_status": "COMPLETE",
    },

    # INV-005: Crypto + UPI + Geospatial Anomaly
    "INV-005": {
        "scenario_id": "INV-005",
        "case_id": "CASE-GEO-ANOMALY-005",
        "title": "Cross-Rail Off-Ramp with Impossible Travel Velocity",
        "description": "Multi-rail chain combined with impossible travel observation across Bengaluru and Delhi.",
        "subject_type": "upi_vpa",
        "subject_id": "traveler@mockupi",
        "rail_scope": "ALL",
        "synthetic": True,
        "provenance": "SYNTHETIC",
        "crypto_transactions": [
            {
                "transaction_hash": "0xddd001",
                "blockchain": "ethereum",
                "timestamp": "2026-09-28T14:00:00Z",
                "from_address": "0x5555555555555555555555555555555555555555",
                "to_address": "0x6666666666666666666666666666666666666666",
                "asset": "ETH",
                "amount": 8.0,
                "transaction_type": "transfer",
            }
        ],
        "vasp_attributions": [
            {
                "wallet_address": "0x6666666666666666666666666666666666666666",
                "vasp_name": "BitQuick Exchange",
                "risk_score": 70.0,
            }
        ],
        "cross_rail_associations": [
            {
                "source_node_id": "wallet:0x6666666666666666666666666666666666666666",
                "target_node_id": "upi:traveler@mockupi",
                "source_rail": "CRYPTO",
                "target_rail": "UPI",
                "confidence": 85.0,
                "description": "SYNTHETIC DEMONSTRATION ASSOCIATION: KYC link to settlement handle.",
            }
        ],
        "upi_transactions": [
            {
                "transaction_id": "UPI-TXN-005-1",
                "timestamp": "2026-09-28T14:15:00Z",
                "amount": 75000.0,
                "currency": "INR",
                "sender_vpa": "traveler@mockupi",
                "receiver_vpa": "recipient1@mockupi",
                "transaction_type": "P2P",
                "status": "SUCCESS",
            },
            {
                "transaction_id": "UPI-TXN-005-2",
                "timestamp": "2026-09-28T14:30:00Z",
                "amount": 75000.0,
                "currency": "INR",
                "sender_vpa": "traveler@mockupi",
                "receiver_vpa": "recipient2@mockupi",
                "transaction_type": "P2P",
                "status": "SUCCESS",
            },
        ],
        "location_signals": [
            {
                "transaction_id": "UPI-TXN-005-1",
                "entity_reference": "upi:traveler@mockupi",
                "timestamp": "2026-09-28T14:15:00Z",
                "latitude": 12.9716,
                "longitude": 77.5946,
                "city": "Bengaluru",
                "country_code": "IN",
                "source": "synthetic",
            },
            {
                "transaction_id": "UPI-TXN-005-2",
                "entity_reference": "upi:traveler@mockupi",
                "timestamp": "2026-09-28T14:30:00Z",
                "latitude": 28.6139,
                "longitude": 77.2090,
                "city": "Delhi",
                "country_code": "IN",
                "source": "synthetic",
            },
        ],
        "expected_risk_level": "CRITICAL",
        "expected_status": "COMPLETE",
    },

    # INV-006: VASP Attribution Investigation
    "INV-006": {
        "scenario_id": "INV-006",
        "case_id": "CASE-VASP-HUB-006",
        "title": "Centralized Exchange Multi-Wallet Consolidation",
        "description": "Multiple independent wallets depositing into centralized VASP with fiat disbursement channel.",
        "subject_type": "entity",
        "subject_id": "Nexus Global VASP",
        "rail_scope": "MULTI_RAIL",
        "synthetic": True,
        "provenance": "MOCK",
        "crypto_transactions": [
            {
                "transaction_hash": "0xeee001",
                "blockchain": "ethereum",
                "timestamp": "2026-09-28T15:00:00Z",
                "from_address": "0xfeeder111111111111111111111111111111111111",
                "to_address": "0xcentralhubexchange000000000000000000000000",
                "asset": "USDT",
                "amount": 20000.0,
                "transaction_type": "transfer",
            },
            {
                "transaction_hash": "0xeee002",
                "blockchain": "ethereum",
                "timestamp": "2026-09-28T15:05:00Z",
                "from_address": "0xfeeder222222222222222222222222222222222222",
                "to_address": "0xcentralhubexchange000000000000000000000000",
                "asset": "USDT",
                "amount": 35000.0,
                "transaction_type": "transfer",
            },
        ],
        "vasp_attributions": [
            {
                "wallet_address": "0xcentralhubexchange000000000000000000000000",
                "vasp_name": "Nexus Global VASP",
                "risk_score": 50.0,
            }
        ],
        "cross_rail_associations": [
            {
                "source_node_id": "vasp:nexus global vasp",
                "target_node_id": "upi:nexus_inr_desk@mockupi",
                "source_rail": "CRYPTO",
                "target_rail": "UPI",
                "confidence": 95.0,
                "description": "SYNTHETIC DEMONSTRATION ASSOCIATION: Institutional banking disbursement channel.",
            }
        ],
        "upi_transactions": [
            {
                "transaction_id": "UPI-TXN-006-1",
                "timestamp": "2026-09-28T15:30:00Z",
                "amount": 1500000.0,
                "currency": "INR",
                "sender_vpa": "nexus_inr_desk@mockupi",
                "receiver_vpa": "distributor_prime@mockupi",
                "transaction_type": "P2P",
                "status": "SUCCESS",
            }
        ],
        "location_signals": [],
        "expected_risk_level": "HIGH",
        "expected_status": "COMPLETE",
    },

    # INV-007: Partial-Data Investigation
    "INV-007": {
        "scenario_id": "INV-007",
        "case_id": "CASE-PARTIAL-DATA-007",
        "title": "Partial Failure Handling (UPI Available, Crypto Unavailable)",
        "description": "Tests resilient investigation execution when crypto intelligence is unavailable/omitted.",
        "subject_type": "upi_vpa",
        "subject_id": "isolated_vpa@mockupi",
        "rail_scope": "MULTI_RAIL",
        "synthetic": True,
        "provenance": "MOCK",
        "crypto_transactions": None,  # Intentionally missing to trigger partial execution
        "vasp_attributions": [],
        "upi_transactions": [
            {
                "transaction_id": "UPI-TXN-007-1",
                "timestamp": "2026-09-28T16:10:00Z",
                "amount": 5000.0,
                "currency": "INR",
                "sender_vpa": "isolated_vpa@mockupi",
                "receiver_vpa": "merchant_isolated@mockupi",
                "transaction_type": "P2M",
                "status": "SUCCESS",
            }
        ],
        "location_signals": [],
        "cross_rail_associations": [],
        "expected_risk_level": "LOW",
        "expected_status": "PARTIAL",
    },

    # INV-008: Benign Control Investigation
    "INV-008": {
        "scenario_id": "INV-008",
        "case_id": "CASE-CONTROL-008",
        "title": "Benign Multi-Rail Retail Transactions (Baseline Control)",
        "description": "Standard legitimate retail transactions across both crypto and UPI rails without anomalies.",
        "subject_type": "case",
        "subject_id": "CASE-CONTROL-008",
        "rail_scope": "MULTI_RAIL",
        "synthetic": True,
        "provenance": "MOCK",
        "crypto_transactions": [
            {
                "transaction_hash": "0xctl001",
                "blockchain": "ethereum",
                "timestamp": "2026-09-28T08:00:00Z",
                "from_address": "0xretail_alice0000000000000000000000000001",
                "to_address": "0xretail_bob00000000000000000000000000000001",
                "asset": "ETH",
                "amount": 0.05,
                "transaction_type": "transfer",
            }
        ],
        "vasp_attributions": [],
        "upi_transactions": [
            {
                "transaction_id": "UPI-TXN-CTL-1",
                "timestamp": "2026-09-28T08:15:00Z",
                "amount": 450.0,
                "currency": "INR",
                "sender_vpa": "grocery_customer@mockupi",
                "receiver_vpa": "daily_mart@mockupi",
                "merchant_id": "MERCH_GROCERY_99",
                "merchant_category": "5411",
                "transaction_type": "P2M",
                "status": "SUCCESS",
            }
        ],
        "location_signals": [],
        "cross_rail_associations": [],
        "expected_risk_level": "LOW",
        "expected_status": "COMPLETE",
    },
}
