import React, { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import { FileText, Printer, Send } from 'lucide-react';
import { api } from '../../services/api';
import './Report.css';

const Report = () => {
  const { caseId } = useParams();
  const [caseData, setCaseData] = useState(null);
  const [isSubmitting, setIsSubmitting] = useState(false);

  useEffect(() => {
    api.getCase(caseId).then(setCaseData);
  }, [caseId]);

  const handleDisclosure = () => {
    setIsSubmitting(true);
    setTimeout(() => {
      alert(`Disclosure Request Prepared for ${caseId}\n\nNote: This is a demo. No data was actually sent to SAHYOG.`);
      setIsSubmitting(false);
    }, 1500);
  };

  if (!caseData) return <div className="loading mono">GENERATING REPORT...</div>;

  return (
    <div className="report-container">
      <div className="report-actions mb-6">
        <button className="btn btn-outline">
          <Printer size={16} /> Print Report
        </button>
        <button className="btn btn-primary" onClick={handleDisclosure} disabled={isSubmitting}>
          {isSubmitting ? 'PREPARING...' : (
            <>
              <Send size={16} /> Prepare SAHYOG Disclosure Request
            </>
          )}
        </button>
      </div>

      <div className="report-document card">
        <div className="report-header">
          <div className="report-brand">TRACEVAULT INTELLIGENCE REPORT</div>
          <div className="report-meta">
            <div><strong>CASE ID:</strong> <span className="mono">{caseId}</span></div>
            <div><strong>DATE:</strong> {new Date(caseData.created).toLocaleDateString()}</div>
            <div><strong>CLASSIFICATION:</strong> CONFIDENTIAL</div>
          </div>
        </div>

        <div className="report-section">
          <h3>1. Executive Summary</h3>
          <p>{caseData.summary}</p>
        </div>

        <div className="report-section">
          <h3>2. Subject Details</h3>
          <table className="report-table">
            <tbody>
              <tr>
                <td><strong>Target Address</strong></td>
                <td className="mono">{caseData.subjectWallet}</td>
              </tr>
              <tr>
                <td><strong>Blockchain</strong></td>
                <td className="uppercase">{caseData.blockchain}</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div className="report-section">
          <h3>3. Risk & Attribution Findings</h3>
          <table className="report-table">
            <tbody>
              <tr>
                <td><strong>Assessed Risk Level</strong></td>
                <td><span className={`badge ${caseData.riskLevel.toLowerCase()}`}>{caseData.riskLevel}</span> (Score: {caseData.riskScore}/100)</td>
              </tr>
              <tr>
                <td><strong>Probable VASP Attribution</strong></td>
                <td><strong>{caseData.attribution.entity}</strong> ({caseData.attribution.type})</td>
              </tr>
              <tr>
                <td><strong>Attribution Confidence</strong></td>
                <td>{caseData.attribution.confidence}%</td>
              </tr>
              <tr>
                <td><strong>Trace Distance</strong></td>
                <td>{caseData.attribution.distance} hops</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div className="report-footer mt-6 text-muted" style={{ fontSize: '0.75rem', textAlign: 'center', borderTop: '1px solid var(--border-highlight)', paddingTop: 'var(--spacing-4)' }}>
          GENERATED BY TRACEVAULT AUTOMATED INTELLIGENCE ENGINE. <br/>
          THIS REPORT CONTAINS PRELIMINARY INTELLIGENCE AND SHOULD BE VERIFIED BY AN INVESTIGATOR.
        </div>
      </div>
    </div>
  );
};

export default Report;
