/**
 * TRACEVAULT RBAC & Permission Matrix
 * Explicit, centralized definition of roles and capabilities.
 */

const ROLES = {
  INVESTIGATOR: 'INVESTIGATOR',
  SUPERVISOR: 'SUPERVISOR',
  ADMIN: 'ADMIN'
};

const PERMISSIONS = {
  // Case permissions
  CASES_VIEW_ASSIGNED: 'CASES_VIEW_ASSIGNED',
  CASES_VIEW_ALL: 'CASES_VIEW_ALL',
  CASES_CREATE: 'CASES_CREATE',
  CASES_MANAGE: 'CASES_MANAGE',

  // Analysis permissions
  ANALYSIS_RUN: 'ANALYSIS_RUN',
  ANALYSIS_VIEW: 'ANALYSIS_VIEW',

  // Evidence & Report permissions
  EVIDENCE_VIEW: 'EVIDENCE_VIEW',
  REPORTS_VIEW: 'REPORTS_VIEW',
  REPORTS_REVIEW: 'REPORTS_REVIEW',

  // Disclosure permissions
  DISCLOSURE_CREATE: 'DISCLOSURE_CREATE',
  DISCLOSURE_REVIEW: 'DISCLOSURE_REVIEW',

  // Supervisory & Audit permissions
  INVESTIGATIONS_REVIEW: 'INVESTIGATIONS_REVIEW',
  AUDIT_VIEW: 'AUDIT_VIEW',

  // System Administration
  USERS_MANAGE: 'USERS_MANAGE',
  ROLES_MANAGE: 'ROLES_MANAGE',
  SYSTEM_ADMIN: 'SYSTEM_ADMIN'
};

const ROLE_PERMISSIONS = {
  [ROLES.INVESTIGATOR]: [
    PERMISSIONS.CASES_VIEW_ASSIGNED,
    PERMISSIONS.CASES_CREATE,
    PERMISSIONS.ANALYSIS_RUN,
    PERMISSIONS.ANALYSIS_VIEW,
    PERMISSIONS.EVIDENCE_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.DISCLOSURE_CREATE
  ],
  [ROLES.SUPERVISOR]: [
    PERMISSIONS.CASES_VIEW_ASSIGNED,
    PERMISSIONS.CASES_VIEW_ALL,
    PERMISSIONS.CASES_CREATE,
    PERMISSIONS.ANALYSIS_RUN,
    PERMISSIONS.ANALYSIS_VIEW,
    PERMISSIONS.EVIDENCE_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_REVIEW,
    PERMISSIONS.DISCLOSURE_CREATE,
    PERMISSIONS.DISCLOSURE_REVIEW,
    PERMISSIONS.INVESTIGATIONS_REVIEW,
    PERMISSIONS.AUDIT_VIEW
  ],
  [ROLES.ADMIN]: [
    PERMISSIONS.CASES_VIEW_ASSIGNED,
    PERMISSIONS.CASES_VIEW_ALL,
    PERMISSIONS.CASES_CREATE,
    PERMISSIONS.CASES_MANAGE,
    PERMISSIONS.ANALYSIS_RUN,
    PERMISSIONS.ANALYSIS_VIEW,
    PERMISSIONS.EVIDENCE_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_REVIEW,
    PERMISSIONS.DISCLOSURE_CREATE,
    PERMISSIONS.DISCLOSURE_REVIEW,
    PERMISSIONS.INVESTIGATIONS_REVIEW,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.USERS_MANAGE,
    PERMISSIONS.ROLES_MANAGE,
    PERMISSIONS.SYSTEM_ADMIN
  ]
};

/**
 * Checks whether a given role holds a specific permission
 * @param {string} role Role name
 * @param {string} permission Permission string
 * @returns {boolean}
 */
function hasPermission(role, permission) {
  if (!role) return false;
  const permissions = ROLE_PERMISSIONS[role.toUpperCase()];
  if (!permissions) return false;
  return permissions.includes(permission);
}

module.exports = {
  ROLES,
  PERMISSIONS,
  ROLE_PERMISSIONS,
  hasPermission
};
