import { AlertTriangle, Building2, Clock3, Database, MousePointer2, Route, WalletCards } from 'lucide-react'
import Badge from '../common/Badge'
import { formatWallet } from '../../utils/formatWallet'

function labelFor(category){return {suspect:'Suspect Wallet',unknown:'Unknown Wallet',intermediary:'Intermediary',exchange:'Exchange Deposit',vasp:'Likely VASP',risk:'Risk Indicator'}[category]||'Wallet'}

export default function NodeInspector({node}){
  if(!node)return <aside className="node-inspector"><header><span>Node inspector</span><small>Contextual intelligence</small></header><div className="inspector-empty"><MousePointer2 aria-hidden="true"/><strong>Select a graph entity</strong><p>Choose a wallet, intermediary, deposit address, or likely VASP to inspect its mock intelligence context.</p></div></aside>
  const data=node.data
  const metadata=data.metadata||{}
  return <aside className="node-inspector"><header><span>Selected node</span><small className="mono">{node.id}</small></header><div className="inspector-content"><div className="inspector-identity"><WalletCards aria-hidden="true"/><div><span>{labelFor(data.category)}</span><strong className={data.entity?'':'mono'}>{data.entity||formatWallet(data.address)}</strong>{data.address&&data.entity&&<small className="mono">{formatWallet(data.address)}</small>}</div></div>{data.risk&&<Badge tone={data.risk}>{data.risk} indicators</Badge>}<dl className="inspector-facts">{data.entity&&<div><dt>Entity association</dt><dd>Likely associated with {data.entity}<small>Probable VASP</small></dd></div>}{data.confidence&&<div><dt>Attribution confidence</dt><dd>{data.confidence}%</dd></div>}{metadata.pathDistance&&<div><dt>Path distance</dt><dd><Route aria-hidden="true"/>{metadata.pathDistance}</dd></div>}{metadata.evidenceSource&&<div><dt>Evidence source</dt><dd><Database aria-hidden="true"/>{metadata.evidenceSource}</dd></div>}{metadata.inbound&&<div><dt>Transaction context</dt><dd><span>Inbound</span>{metadata.inbound}<small><span>Outbound</span>{metadata.outbound}</small></dd></div>}{metadata.transactionCount!==undefined&&<div><dt>Transaction count</dt><dd>{metadata.transactionCount}</dd></div>}<div><dt>Observed window</dt><dd><Clock3 aria-hidden="true"/>{metadata.firstSeen}<small>{metadata.lastSeen}</small></dd></div></dl><section className="indicator-section"><h3><AlertTriangle aria-hidden="true"/>Risk indicators</h3>{metadata.indicators?.length?<ul>{metadata.indicators.map(item=><li key={item}>{item}</li>)}</ul>:<p>No specific indicators attached to this mock entity.</p>}</section><p className="inspector-disclaimer"><Building2 aria-hidden="true"/>Associations and indicators are fictional analytical context, not ownership claims or proof of wrongdoing.</p></div></aside>
}
